package pojo;
// Generated Jan 19, 2019 8:56:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Poeti generated by hbm2java
 */
public class Poeti  implements java.io.Serializable {


     private Integer idpoet;
     private String nume;
     private String prenume;
     private String nationalitate;
     private Set<Volumpoezii> volumpoeziis = new HashSet<Volumpoezii>(0);

    public Poeti() {
    }

    public Poeti(String nume, String prenume, String nationalitate, Set<Volumpoezii> volumpoeziis) {
       this.nume = nume;
       this.prenume = prenume;
       this.nationalitate = nationalitate;
       this.volumpoeziis = volumpoeziis;
    }
   
    public Integer getIdpoet() {
        return this.idpoet;
    }
    
    public void setIdpoet(Integer idpoet) {
        this.idpoet = idpoet;
    }
    public String getNume() {
        return this.nume;
    }
    
    public void setNume(String nume) {
        this.nume = nume;
    }
    public String getPrenume() {
        return this.prenume;
    }
    
    public void setPrenume(String prenume) {
        this.prenume = prenume;
    }
    public String getNationalitate() {
        return this.nationalitate;
    }
    
    public void setNationalitate(String nationalitate) {
        this.nationalitate = nationalitate;
    }
    public Set<Volumpoezii> getVolumpoeziis() {
        return this.volumpoeziis;
    }
    
    public void setVolumpoeziis(Set<Volumpoezii> volumpoeziis) {
        this.volumpoeziis = volumpoeziis;
    }




}


