package pojo;
// Generated Jan 19, 2019 8:56:43 PM by Hibernate Tools 4.3.1



/**
 * Volumpoezii generated by hbm2java
 */
public class Volumpoezii  implements java.io.Serializable {


     private Integer idvolumpoezii;
     private Carti carti;
     private Poeti poeti;
     private String numeVolum;
     private String dataLansare;
     private String tema;

    public Volumpoezii() {
    }

    public Volumpoezii(Carti carti, Poeti poeti, String numeVolum, String dataLansare, String tema) {
       this.carti = carti;
       this.poeti = poeti;
       this.numeVolum = numeVolum;
       this.dataLansare = dataLansare;
       this.tema = tema;
    }
   
    public Integer getIdvolumpoezii() {
        return this.idvolumpoezii;
    }
    
    public void setIdvolumpoezii(Integer idvolumpoezii) {
        this.idvolumpoezii = idvolumpoezii;
    }
    public Carti getCarti() {
        return this.carti;
    }
    
    public void setCarti(Carti carti) {
        this.carti = carti;
    }
    public Poeti getPoeti() {
        return this.poeti;
    }
    
    public void setPoeti(Poeti poeti) {
        this.poeti = poeti;
    }
    public String getNumeVolum() {
        return this.numeVolum;
    }
    
    public void setNumeVolum(String numeVolum) {
        this.numeVolum = numeVolum;
    }
    public String getDataLansare() {
        return this.dataLansare;
    }
    
    public void setDataLansare(String dataLansare) {
        this.dataLansare = dataLansare;
    }
    public String getTema() {
        return this.tema;
    }
    
    public void setTema(String tema) {
        this.tema = tema;
    }




}


